### ISSUE TITLE
First try on the project

### ISSUE THREAD

**Issue by ktfth** [willgm/web-crypto-storage#10]
Using the application for the first time on the repository an failure appear to me like that:

rollup v2.32.1
bundles src/web-crypto-storage.ts → dist/web-crypto-storage.cjs.js, dist/web-crypto-storage.module.js, dist/web-crypto-storage.umd.js...
[0000] info  LiveReload running
Error: Can't walk dependency graph: Cannot find module '../dist/web-crypto-storage.cjs' from '/home/kaique/war/web-crypto-storage/demo/demo.js'
    required by /home/kaique/war/web-crypto-storage/demo/demo.js
    at /home/kaique/war/web-crypto-storage/node_modules/resolve/lib/async.js:136:35
    at load (/home/kaique/war/web-crypto-storage/node_modules/resolve/lib/async.js:155:43)
    at onex (/home/kaique/war/web-crypto-storage/node_modules/resolve/lib/async.js:180:17)
    at /home/kaique/war/web-crypto-storage/node_modules/resolve/lib/async.js:15:69
    at FSReqCallback.oncomplete (fs.js:168:21) {
  code: 'MODULE_NOT_FOUND',
  stream: [Labeled]
}
created dist/web-crypto-storage.cjs.js, dist/web-crypto-storage.module.js, dist/web-crypto-storage.umd.js in 1.8s
bundles src/web-crypto-storage.ts → dist/web-crypto-storage.es2015.js...
created dist/web-crypto-storage.es2015.js in 1.2s

[2020-11-14 19:13:52] waiting for changes...

Can you help with that?

**Comment by willgm** [comment]
Hello @ktfth!

As we discussed by pm, I need more details about the command were you running, which version of NodeJS, npm and etc.

I gonna close this issue until you give more details, then we can reopen.

Until then I will make a issue template to guide the next open issues.

Thanks,
William
