### ISSUE TITLE
Is it intended to have mangled db and collection names?

### ISSUE THREAD

**Issue by ohager** [willgm/web-crypto-storage#16]
This is rather a question out of curiosity...But I really wondered about the mangled names in IndexedDB.

![image](https://user-images.githubusercontent.com/3920663/126042462-bcbb376f-0f15-40de-ba11-e307c211ed86.png)

Tested using Chrome Version 91.0.4472.101 (Official Build) (64-bit) and Firefox 90

**Comment by jzombie** [comment]
I would think, yes, because it is encrypted.

**Comment by willgm** [comment]
Yes, it is an expected behavior. All the table names and keys are stored as hash using `SHA-256`, as your code should know then before trying to access, their value cannot be reverted to the original, resulting in a little more privacy.
